name: versioning

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: |
          echo "date={$(date +'%Y.%m')}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/${{ steps.date.outputs.date }}
  call-docker:
    permissions:
      contents: read
      packages: write
    if: always() && contains(join(needs.*.result, ','), 'success')
    needs: [create-branch]
    uses: ./.github/workflows/docker.yml
